name: purr_pedia_app
description: "A technical test for pragma"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.1.4
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.5.0+1

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/colors/
    - assets/envs/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/caveat/Caveat-Bold.ttf
        - asset: assets/fonts/caveat/Caveat-Medium.ttf
        - asset: assets/fonts/caveat/Caveat-Regular.ttf
        - asset: assets/fonts/caveat/Caveat-SemiBold.ttf
        - asset: assets/fonts/caveat/Caveat-VariableFont_wght.ttf

flutter_gen:
  output: lib/core/config/design/gen
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    outputs:
      class_name: AssetsToken
  fonts:
    enabled: true
    outputs:
      class_name: FontFamilyToken
  colors:
    enabled: true
    outputs:
      class_name: ColorsToken
    inputs:
      - assets/colors/colors.xml
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
